import streamlit as st

def about_show () :
    st.title('프로젝트 정보')

    st.markdown('#### TensorFlow Object Detection TFOD (텐서플로 사물 탐지)기능을 이용해')
    st.markdown('#### 원하는 정지 영상(그림 및 사진)이나 동영상에 어떤 물체가 있는지')
    st.markdown('#### 판별 및 시각화하는 웹 대시보드 입니다.')
    st.markdown('---')
    st.markdown('##### 왼쪽 사이드바 메뉴 (날개)에서 메뉴와 인공지능 모델, 시각화할 예측 확률을 설정할 수 있습니다.')
    st.markdown('---')
    st.markdown('**기본 모델**은 중간정도의 성능과 정확도를 가진 모델입니다.')
    st.markdown('###### SSD ResNet101 V1 FPN 1024x1024 (RetinaNet101) 모델 사용')
    st.write('')
    st.markdown('**저품질 모델**은 정확도가 낮지만 빠르게 작동합니다.')
    st.markdown('###### SSD MobileNet v2 320x320 모델 사용')
    st.write('')
    st.markdown('**느린 고품질 모델**은 작업속도가 느린 대신 보다 정확한 결과를 제공합니다.')
    st.markdown('###### CenterNet HourGlass104 1024x1024 모델 사용')
    st.markdown('---')
    st.markdown('그 외에도 TensorFlow 2 Detection Model Zoo의 다른 모델의 주소를 **직접 입력**할 수 있습니다.')
    st.write('https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md')
    st.markdown('링크 주소 복사를 통해 **url**을 가져와야 한다는 점을 기억하세요.')
    st.markdown('---')
    st.write('각 모델은 처음 실행할 때 모델을 다운로드 하는 시간이 추가로 소요되며 경우에 따라 재실행해야 할 수도 있습니다.')
    st.write('다음 동작부터는 보다 빨라집니다.')

    st.write('정지 영상(그림 및 사진)과 동영상을 분석할 수 있으며')
    st.write('컴퓨터에 저장된 파일을 직접 업로드하거나, url주소를 이용할 수 있습니다.')
    st.write('.png, .jpg, .jpeg 형식의 정지 영상을 업로드 할 수 있습니다.')
    st.write('.avi, .mp4, .wmv 형식의 동영상을 업로드 할 수 있습니다.')
    st.write('')
    st.write('일부 url은 보안상 반려됩니다.')
    st.write('동영상 url은 현재 YouTube만 가능합니다.')